defmodule Fitconnex.Repo.Migrations.AddBranchToMemberInvitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:member_invitations) do
      add :branch_id,
          references(:gym_branches,
            column: :id,
            name: "member_invitations_branch_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:member_invitations, "member_invitations_branch_id_fkey")

    alter table(:member_invitations) do
      remove :branch_id
    end
  end
end
