defmodule FitTrackerz.Repo.Migrations.RemoveGymTier do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:gyms) do
      remove :tier
    end
  end

  def down do
    alter table(:gyms) do
      add :tier, :text, null: false, default: "free"
    end
  end
end
