defmodule Fitconnex.Repo.Migrations.AddContests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:contests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :contest_type, :text, null: false
      add :status, :text, null: false, default: "upcoming"
      add :starts_at, :utc_datetime, null: false
      add :ends_at, :utc_datetime, null: false
      add :max_participants, :bigint
      add :prize_description, :text
      add :banner_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "contests_gym_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :branch_id,
          references(:gym_branches,
            column: :id,
            name: "contests_branch_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:contests, [:status])

    create index(:contests, [:gym_id])
  end

  def down do
    drop constraint(:contests, "contests_gym_id_fkey")

    drop constraint(:contests, "contests_branch_id_fkey")

    drop_if_exists index(:contests, [:gym_id])

    drop_if_exists index(:contests, [:status])

    drop table(:contests)
  end
end
