defmodule Fitconnex.Repo.Migrations.AddFeaturesAndCategoryToSubscriptionPlans do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subscription_plans) do
      add :features, {:array, :text}, default: []
    end

    alter table(:gyms) do
      add :phone, :text
      add :equipment, {:array, :text}, default: []
      add :services, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:gyms) do
      remove :services
      remove :equipment
      remove :phone
    end

    alter table(:subscription_plans) do
      remove :features
    end
  end
end
