defmodule FitTrackerz.Repo.Migrations.CreateFitTrackerzResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workout_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :exercises, {:array, :map}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :member_id, :uuid, null: false
      add :gym_id, :uuid, null: false
      add :trainer_id, :uuid
      add :template_id, :uuid
    end

    create table(:workout_plan_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :exercises, {:array, :map}, default: []
      add :difficulty_level, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id, :uuid, null: false
      add :created_by_id, :uuid, null: false
    end

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :name, :text, null: false
      add :phone, :text
      add :role, :text, null: false, default: "member"
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:trainer_invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :invited_email, :citext, null: false
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id, :uuid, null: false
      add :invited_by_id, :uuid, null: false
    end

    create table(:subscription_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :plan_type, :text, null: false
      add :duration, :text, null: false
      add :price_in_paise, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id, :uuid, null: false
    end

    create table(:scheduled_classes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :scheduled_at, :utc_datetime, null: false
      add :duration_minutes, :bigint, null: false
      add :status, :text, null: false, default: "scheduled"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :class_definition_id, :uuid, null: false
      add :branch_id, :uuid, null: false
      add :trainer_id, :uuid
    end

    create table(:member_subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "active"
      add :starts_at, :utc_datetime, null: false
      add :ends_at, :utc_datetime, null: false
      add :payment_status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :member_id, :uuid, null: false
      add :subscription_plan_id, :uuid, null: false
      add :gym_id, :uuid, null: false
    end

    create table(:member_invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :invited_email, :citext, null: false
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id, :uuid, null: false
      add :invited_by_id, :uuid, null: false
    end

    create table(:gyms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:workout_plan_templates) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "workout_plan_templates_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :created_by_id,
             references(:users,
               column: :id,
               name: "workout_plan_templates_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:trainer_invitations) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "trainer_invitations_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :invited_by_id,
             references(:users,
               column: :id,
               name: "trainer_invitations_invited_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:subscription_plans) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "subscription_plans_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:member_invitations) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "member_invitations_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :invited_by_id,
             references(:users,
               column: :id,
               name: "member_invitations_invited_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:gyms) do
      add :name, :text, null: false
      add :slug, :citext, null: false
      add :description, :text
      add :status, :text, null: false, default: "pending_verification"
      add :is_promoted, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "gyms_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:gyms, [:slug], name: "gyms_unique_slug_index")

    create table(:gym_trainers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :specializations, {:array, :text}, default: []
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "gym_trainers_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "gym_trainers_gym_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:gym_trainers, [:user_id, :gym_id],
             name: "gym_trainers_unique_trainer_gym_index"
           )

    create table(:gym_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:workout_plans) do
      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "workout_plans_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "workout_plans_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :trainer_id,
             references(:users,
               column: :id,
               name: "workout_plans_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :template_id,
             references(:workout_plan_templates,
               column: :id,
               name: "workout_plans_template_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:member_subscriptions) do
      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "member_subscriptions_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :subscription_plan_id,
             references(:subscription_plans,
               column: :id,
               name: "member_subscriptions_subscription_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "member_subscriptions_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:gym_members) do
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "gym_members_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "gym_members_gym_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :assigned_trainer_id,
          references(:users,
            column: :id,
            name: "gym_members_assigned_trainer_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:gym_members, [:user_id, :gym_id],
             name: "gym_members_unique_membership_index"
           )

    create table(:gym_branches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :address, :text, null: false
      add :city, :text, null: false
      add :state, :text, null: false
      add :postal_code, :text, null: false
      add :latitude, :float
      add :longitude, :float
      add :is_primary, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "gym_branches_gym_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:diet_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :meals, {:array, :map}, default: []
      add :calorie_target, :bigint
      add :dietary_type, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :member_id,
          references(:gym_members,
            column: :id,
            name: "diet_plans_member_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "diet_plans_gym_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :trainer_id,
          references(:users,
            column: :id,
            name: "diet_plans_trainer_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :template_id, :uuid
    end

    create table(:diet_plan_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:diet_plans) do
      modify :template_id,
             references(:diet_plan_templates,
               column: :id,
               name: "diet_plans_template_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:diet_plan_templates) do
      add :name, :text, null: false
      add :meals, {:array, :map}, default: []
      add :calorie_target, :bigint
      add :dietary_type, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "diet_plan_templates_gym_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "diet_plan_templates_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:class_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:scheduled_classes) do
      modify :class_definition_id,
             references(:class_definitions,
               column: :id,
               name: "scheduled_classes_class_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :branch_id,
             references(:gym_branches,
               column: :id,
               name: "scheduled_classes_branch_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :trainer_id,
             references(:users,
               column: :id,
               name: "scheduled_classes_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:class_definitions) do
      add :name, :text, null: false
      add :class_type, :text, null: false
      add :default_duration_minutes, :bigint, null: false
      add :max_participants, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "class_definitions_gym_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:class_bookings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :scheduled_class_id,
          references(:scheduled_classes,
            column: :id,
            name: "class_bookings_scheduled_class_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :member_id,
          references(:gym_members,
            column: :id,
            name: "class_bookings_member_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:class_bookings, [:scheduled_class_id, :member_id],
             name: "class_bookings_unique_booking_index"
           )

    create table(:attendance_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :attended_at, :utc_datetime, null: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :member_id,
          references(:gym_members,
            column: :id,
            name: "attendance_records_member_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "attendance_records_gym_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :marked_by_id,
          references(:users,
            column: :id,
            name: "attendance_records_marked_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:attendance_records, "attendance_records_member_id_fkey")

    drop constraint(:attendance_records, "attendance_records_gym_id_fkey")

    drop constraint(:attendance_records, "attendance_records_marked_by_id_fkey")

    drop table(:attendance_records)

    drop_if_exists unique_index(:class_bookings, [:scheduled_class_id, :member_id],
                     name: "class_bookings_unique_booking_index"
                   )

    drop constraint(:class_bookings, "class_bookings_scheduled_class_id_fkey")

    drop constraint(:class_bookings, "class_bookings_member_id_fkey")

    drop table(:class_bookings)

    drop constraint(:class_definitions, "class_definitions_gym_id_fkey")

    alter table(:class_definitions) do
      remove :gym_id
      remove :updated_at
      remove :inserted_at
      remove :max_participants
      remove :default_duration_minutes
      remove :class_type
      remove :name
    end

    drop constraint(:scheduled_classes, "scheduled_classes_class_definition_id_fkey")

    drop constraint(:scheduled_classes, "scheduled_classes_branch_id_fkey")

    drop constraint(:scheduled_classes, "scheduled_classes_trainer_id_fkey")

    alter table(:scheduled_classes) do
      modify :trainer_id, :uuid
      modify :branch_id, :uuid
      modify :class_definition_id, :uuid
    end

    drop table(:class_definitions)

    drop constraint(:diet_plan_templates, "diet_plan_templates_gym_id_fkey")

    drop constraint(:diet_plan_templates, "diet_plan_templates_created_by_id_fkey")

    alter table(:diet_plan_templates) do
      remove :created_by_id
      remove :gym_id
      remove :updated_at
      remove :inserted_at
      remove :dietary_type
      remove :calorie_target
      remove :meals
      remove :name
    end

    drop constraint(:diet_plans, "diet_plans_template_id_fkey")

    alter table(:diet_plans) do
      modify :template_id, :uuid
    end

    drop table(:diet_plan_templates)

    drop constraint(:diet_plans, "diet_plans_member_id_fkey")

    drop constraint(:diet_plans, "diet_plans_gym_id_fkey")

    drop constraint(:diet_plans, "diet_plans_trainer_id_fkey")

    drop table(:diet_plans)

    drop constraint(:gym_branches, "gym_branches_gym_id_fkey")

    drop table(:gym_branches)

    drop_if_exists unique_index(:gym_members, [:user_id, :gym_id],
                     name: "gym_members_unique_membership_index"
                   )

    drop constraint(:gym_members, "gym_members_user_id_fkey")

    drop constraint(:gym_members, "gym_members_gym_id_fkey")

    drop constraint(:gym_members, "gym_members_assigned_trainer_id_fkey")

    alter table(:gym_members) do
      remove :assigned_trainer_id
      remove :gym_id
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :is_active
    end

    drop constraint(:member_subscriptions, "member_subscriptions_member_id_fkey")

    drop constraint(:member_subscriptions, "member_subscriptions_subscription_plan_id_fkey")

    drop constraint(:member_subscriptions, "member_subscriptions_gym_id_fkey")

    alter table(:member_subscriptions) do
      modify :gym_id, :uuid
      modify :subscription_plan_id, :uuid
      modify :member_id, :uuid
    end

    drop constraint(:workout_plans, "workout_plans_member_id_fkey")

    drop constraint(:workout_plans, "workout_plans_gym_id_fkey")

    drop constraint(:workout_plans, "workout_plans_trainer_id_fkey")

    drop constraint(:workout_plans, "workout_plans_template_id_fkey")

    alter table(:workout_plans) do
      modify :template_id, :uuid
      modify :trainer_id, :uuid
      modify :gym_id, :uuid
      modify :member_id, :uuid
    end

    drop table(:gym_members)

    drop_if_exists unique_index(:gym_trainers, [:user_id, :gym_id],
                     name: "gym_trainers_unique_trainer_gym_index"
                   )

    drop constraint(:gym_trainers, "gym_trainers_user_id_fkey")

    drop constraint(:gym_trainers, "gym_trainers_gym_id_fkey")

    drop table(:gym_trainers)

    drop_if_exists unique_index(:gyms, [:slug], name: "gyms_unique_slug_index")

    drop constraint(:gyms, "gyms_owner_id_fkey")

    alter table(:gyms) do
      remove :owner_id
      remove :updated_at
      remove :inserted_at
      remove :is_promoted
      remove :status
      remove :description
      remove :slug
      remove :name
    end

    drop constraint(:member_invitations, "member_invitations_gym_id_fkey")

    drop constraint(:member_invitations, "member_invitations_invited_by_id_fkey")

    alter table(:member_invitations) do
      modify :invited_by_id, :uuid
      modify :gym_id, :uuid
    end

    drop constraint(:subscription_plans, "subscription_plans_gym_id_fkey")

    alter table(:subscription_plans) do
      modify :gym_id, :uuid
    end

    drop constraint(:trainer_invitations, "trainer_invitations_gym_id_fkey")

    drop constraint(:trainer_invitations, "trainer_invitations_invited_by_id_fkey")

    alter table(:trainer_invitations) do
      modify :invited_by_id, :uuid
      modify :gym_id, :uuid
    end

    drop constraint(:workout_plan_templates, "workout_plan_templates_gym_id_fkey")

    drop constraint(:workout_plan_templates, "workout_plan_templates_created_by_id_fkey")

    alter table(:workout_plan_templates) do
      modify :created_by_id, :uuid
      modify :gym_id, :uuid
    end

    drop table(:gyms)

    drop table(:member_invitations)

    drop table(:member_subscriptions)

    drop table(:scheduled_classes)

    drop table(:subscription_plans)

    drop table(:trainer_invitations)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)

    drop table(:workout_plan_templates)

    drop table(:workout_plans)
  end
end
