defmodule FitTrackerz.Repo.Migrations.AddImagesToGymBranches do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :name, :text, default: "User"
    end

    alter table(:gym_branches) do
      add :logo_url, :text
      add :gallery_urls, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:gym_branches) do
      remove :gallery_urls
      remove :logo_url
    end

    alter table(:users) do
      modify :name, :text, default: nil
    end
  end
end
