defmodule Fitconnex.Repo.Migrations.AddBranchToMembersAndTrainers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:workout_plans, "workout_plans_trainer_id_fkey")

    alter table(:workout_plans) do
      modify :trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "workout_plans_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:scheduled_classes, "scheduled_classes_trainer_id_fkey")

    alter table(:scheduled_classes) do
      modify :trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "scheduled_classes_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:gym_trainers) do
      add :branch_id,
          references(:gym_branches,
            column: :id,
            name: "gym_trainers_branch_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop constraint(:gym_members, "gym_members_assigned_trainer_id_fkey")

    alter table(:gym_members) do
      add :branch_id,
          references(:gym_branches,
            column: :id,
            name: "gym_members_branch_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      modify :assigned_trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "gym_members_assigned_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:diet_plans, "diet_plans_trainer_id_fkey")

    alter table(:diet_plans) do
      modify :trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "diet_plans_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:diet_plans, "diet_plans_trainer_id_fkey")

    alter table(:diet_plans) do
      modify :trainer_id,
             references(:users,
               column: :id,
               name: "diet_plans_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:gym_members, "gym_members_branch_id_fkey")

    drop constraint(:gym_members, "gym_members_assigned_trainer_id_fkey")

    alter table(:gym_members) do
      modify :assigned_trainer_id,
             references(:users,
               column: :id,
               name: "gym_members_assigned_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      remove :branch_id
    end

    drop constraint(:gym_trainers, "gym_trainers_branch_id_fkey")

    alter table(:gym_trainers) do
      remove :branch_id
    end

    drop constraint(:scheduled_classes, "scheduled_classes_trainer_id_fkey")

    alter table(:scheduled_classes) do
      modify :trainer_id,
             references(:users,
               column: :id,
               name: "scheduled_classes_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:workout_plans, "workout_plans_trainer_id_fkey")

    alter table(:workout_plans) do
      modify :trainer_id,
             references(:users,
               column: :id,
               name: "workout_plans_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
