defmodule FitTrackerz.Repo.Migrations.Phase2Backend do
  @moduledoc """
  Phase 2 backend: gamification streaks, QR check-ins, body measurements,
  progress photos, and gym tier gating.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and then manually trimmed to only include Phase 2 changes (pre-existing
  tables from snapshot drift were removed).
  """

  use Ecto.Migration

  def up do
    create table(:gamification_streaks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :streak_type, :text, null: false
      add :current_streak, :bigint, null: false, default: 0
      add :longest_streak, :bigint, null: false, default: 0
      add :last_activity_date, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_member_id,
          references(:gym_members,
            column: :id,
            name: "gamification_streaks_gym_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:gamification_streaks, [:gym_member_id, :streak_type])
    create index(:gamification_streaks, [:gym_member_id])

    create unique_index(:gamification_streaks, [:gym_member_id, :streak_type],
             name: "gamification_streaks_unique_member_streak_type_index"
           )

    create table(:gamification_streak_milestones, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :streak_type, :text, null: false
      add :milestone_days, :bigint, null: false
      add :achieved_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_member_id,
          references(:gym_members,
            column: :id,
            name: "gamification_streak_milestones_gym_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:gamification_streak_milestones, [:gym_member_id])

    create unique_index(
             :gamification_streak_milestones,
             [:gym_member_id, :streak_type, :milestone_days],
             name: "gamification_streak_milestones_unique_member_milestone_index"
           )

    create table(:health_body_measurements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :recorded_on, :date, null: false
      add :weight_kg, :decimal
      add :body_fat_pct, :decimal
      add :muscle_mass_kg, :decimal
      add :chest_cm, :decimal
      add :waist_cm, :decimal
      add :hips_cm, :decimal
      add :bicep_cm, :decimal
      add :thigh_cm, :decimal
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :member_id,
          references(:gym_members,
            column: :id,
            name: "health_body_measurements_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:health_body_measurements, [:member_id, :recorded_on])
    create index(:health_body_measurements, [:member_id])

    create unique_index(:health_body_measurements, [:member_id, :recorded_on],
             name: "health_body_measurements_unique_member_date_index"
           )

    create table(:health_progress_photos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :taken_on, :date, null: false
      add :photo_url, :text, null: false
      add :category, :text, null: false, default: "front"
      add :shared_with_trainer, :boolean, null: false, default: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :member_id,
          references(:gym_members,
            column: :id,
            name: "health_progress_photos_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:health_progress_photos, [:member_id, :taken_on])
    create index(:health_progress_photos, [:member_id])

    create table(:training_qr_check_ins, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :used_at, :utc_datetime
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_member_id,
          references(:gym_members,
            column: :id,
            name: "training_qr_check_ins_gym_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :gym_branch_id,
          references(:gym_branches,
            column: :id,
            name: "training_qr_check_ins_gym_branch_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:training_qr_check_ins, [:token])
    create index(:training_qr_check_ins, [:gym_member_id])

    create unique_index(:training_qr_check_ins, [:token],
             name: "training_qr_check_ins_unique_token_index"
           )

    alter table(:gyms) do
      add :tier, :text, null: false, default: "free"
    end
  end

  def down do
    alter table(:gyms) do
      remove :tier
    end

    drop_if_exists unique_index(:training_qr_check_ins, [:token],
                     name: "training_qr_check_ins_unique_token_index"
                   )

    drop constraint(:training_qr_check_ins, "training_qr_check_ins_gym_member_id_fkey")
    drop constraint(:training_qr_check_ins, "training_qr_check_ins_gym_branch_id_fkey")
    drop_if_exists index(:training_qr_check_ins, [:gym_member_id])
    drop_if_exists index(:training_qr_check_ins, [:token])
    drop table(:training_qr_check_ins)

    drop constraint(:health_progress_photos, "health_progress_photos_member_id_fkey")
    drop_if_exists index(:health_progress_photos, [:member_id])
    drop_if_exists index(:health_progress_photos, [:member_id, :taken_on])
    drop table(:health_progress_photos)

    drop_if_exists unique_index(:health_body_measurements, [:member_id, :recorded_on],
                     name: "health_body_measurements_unique_member_date_index"
                   )

    drop constraint(:health_body_measurements, "health_body_measurements_member_id_fkey")
    drop_if_exists index(:health_body_measurements, [:member_id])
    drop_if_exists index(:health_body_measurements, [:member_id, :recorded_on])
    drop table(:health_body_measurements)

    drop_if_exists unique_index(
                     :gamification_streak_milestones,
                     [:gym_member_id, :streak_type, :milestone_days],
                     name: "gamification_streak_milestones_unique_member_milestone_index"
                   )

    drop constraint(
           :gamification_streak_milestones,
           "gamification_streak_milestones_gym_member_id_fkey"
         )

    drop_if_exists index(:gamification_streak_milestones, [:gym_member_id])
    drop table(:gamification_streak_milestones)

    drop_if_exists unique_index(:gamification_streaks, [:gym_member_id, :streak_type],
                     name: "gamification_streaks_unique_member_streak_type_index"
                   )

    drop constraint(:gamification_streaks, "gamification_streaks_gym_member_id_fkey")
    drop_if_exists index(:gamification_streaks, [:gym_member_id])
    drop_if_exists index(:gamification_streaks, [:gym_member_id, :streak_type])
    drop table(:gamification_streaks)
  end
end
