defmodule FitTrackerz.Repo.Migrations.AddHealthAndWorkoutTracking do
  @moduledoc """
  Creates health_metrics, food_logs, workout_logs, and workout_log_entries tables.

  This file was autogenerated with `mix ash_postgres.generate_migrations` and then
  trimmed to remove trainer-related changes already applied by the
  restore_trainer_functionality migration.
  """

  use Ecto.Migration

  def up do
    create table(:workout_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :completed_on, :date, null: false
      add :duration_minutes, :bigint
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :member_id,
          references(:gym_members,
            column: :id,
            name: "workout_logs_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "workout_logs_gym_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :workout_plan_id,
          references(:workout_plans,
            column: :id,
            name: "workout_logs_workout_plan_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:workout_logs, [:member_id, :completed_on])
    create index(:workout_logs, [:gym_id])
    create index(:workout_logs, [:member_id])

    create table(:workout_log_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :exercise_name, :text, null: false
      add :planned_sets, :bigint
      add :planned_reps, :bigint
      add :actual_sets, :bigint, null: false
      add :actual_reps, :bigint, null: false
      add :weight_kg, :decimal
      add :order, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workout_log_id,
          references(:workout_logs,
            column: :id,
            name: "workout_log_entries_workout_log_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:workout_log_entries, [:workout_log_id])

    create table(:health_metrics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :recorded_on, :date, null: false
      add :weight_kg, :decimal, null: false
      add :height_cm, :decimal
      add :bmi, :decimal
      add :body_fat_pct, :decimal
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :member_id,
          references(:gym_members,
            column: :id,
            name: "health_metrics_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "health_metrics_gym_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:health_metrics, [:gym_id])
    create index(:health_metrics, [:member_id])

    create unique_index(:health_metrics, [:member_id, :recorded_on],
             name: "health_metrics_unique_member_date_index"
           )

    create table(:food_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :logged_on, :date, null: false
      add :meal_type, :text, null: false
      add :food_name, :text, null: false
      add :calories, :bigint, null: false
      add :protein_g, :decimal
      add :carbs_g, :decimal
      add :fat_g, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :member_id,
          references(:gym_members,
            column: :id,
            name: "food_logs_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "food_logs_gym_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:food_logs, [:member_id, :logged_on])
    create index(:food_logs, [:gym_id])
    create index(:food_logs, [:member_id])
  end

  def down do
    drop constraint(:food_logs, "food_logs_member_id_fkey")
    drop constraint(:food_logs, "food_logs_gym_id_fkey")
    drop_if_exists index(:food_logs, [:member_id])
    drop_if_exists index(:food_logs, [:gym_id])
    drop_if_exists index(:food_logs, [:member_id, :logged_on])
    drop table(:food_logs)

    drop_if_exists unique_index(:health_metrics, [:member_id, :recorded_on],
                     name: "health_metrics_unique_member_date_index"
                   )
    drop constraint(:health_metrics, "health_metrics_member_id_fkey")
    drop constraint(:health_metrics, "health_metrics_gym_id_fkey")
    drop_if_exists index(:health_metrics, [:member_id])
    drop_if_exists index(:health_metrics, [:gym_id])
    drop table(:health_metrics)

    drop constraint(:workout_log_entries, "workout_log_entries_workout_log_id_fkey")
    drop_if_exists index(:workout_log_entries, [:workout_log_id])
    drop table(:workout_log_entries)

    drop constraint(:workout_logs, "workout_logs_member_id_fkey")
    drop constraint(:workout_logs, "workout_logs_gym_id_fkey")
    drop constraint(:workout_logs, "workout_logs_workout_plan_id_fkey")
    drop_if_exists index(:workout_logs, [:member_id])
    drop_if_exists index(:workout_logs, [:gym_id])
    drop_if_exists index(:workout_logs, [:member_id, :completed_on])
    drop table(:workout_logs)
  end
end
