defmodule FitTrackerz.Repo.Migrations.CreateClientAssignmentRequests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:client_assignment_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "client_assignment_requests_gym_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :member_id,
          references(:gym_members,
            column: :id,
            name: "client_assignment_requests_member_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :trainer_id,
          references(:gym_trainers,
            column: :id,
            name: "client_assignment_requests_trainer_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :requested_by_id,
          references(:users,
            column: :id,
            name: "client_assignment_requests_requested_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:client_assignment_requests, "client_assignment_requests_gym_id_fkey")

    drop constraint(:client_assignment_requests, "client_assignment_requests_member_id_fkey")

    drop constraint(:client_assignment_requests, "client_assignment_requests_trainer_id_fkey")

    drop constraint(
           :client_assignment_requests,
           "client_assignment_requests_requested_by_id_fkey"
         )

    drop table(:client_assignment_requests)
  end
end
