defmodule Fitconnex.Repo.Migrations.FixGymOwnerCascadeDelete do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:workout_plans, [:gym_id])

    create index(:workout_plans, [:trainer_id])

    create index(:workout_plans, [:member_id])

    drop constraint(:workout_plans, "workout_plans_template_id_fkey")

    drop constraint(:workout_plans, "workout_plans_trainer_id_fkey")

    drop constraint(:workout_plans, "workout_plans_gym_id_fkey")

    drop constraint(:workout_plans, "workout_plans_member_id_fkey")

    alter table(:workout_plans) do
      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "workout_plans_member_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "workout_plans_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "workout_plans_trainer_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :template_id,
             references(:workout_plan_templates,
               column: :id,
               name: "workout_plans_template_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    create index(:workout_plan_templates, [:created_by_id])

    create index(:workout_plan_templates, [:gym_id])

    drop constraint(:workout_plan_templates, "workout_plan_templates_created_by_id_fkey")

    drop constraint(:workout_plan_templates, "workout_plan_templates_gym_id_fkey")

    alter table(:workout_plan_templates) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "workout_plan_templates_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :created_by_id,
             references(:users,
               column: :id,
               name: "workout_plan_templates_created_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    create index(:trainer_invitations, [:invited_email])

    create index(:trainer_invitations, [:gym_id])

    drop constraint(:trainer_invitations, "trainer_invitations_invited_by_id_fkey")

    drop constraint(:trainer_invitations, "trainer_invitations_gym_id_fkey")

    alter table(:trainer_invitations) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "trainer_invitations_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :invited_by_id,
             references(:users,
               column: :id,
               name: "trainer_invitations_invited_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    create unique_index(:trainer_invitations, [:gym_id, :invited_email],
             name: "trainer_invitations_unique_pending_invitation_index",
             where: "(status = 'pending')"
           )

    create index(:subscription_plans, [:gym_id])

    drop constraint(:subscription_plans, "subscription_plans_gym_id_fkey")

    alter table(:subscription_plans) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "subscription_plans_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:scheduled_classes, [:class_definition_id])

    create index(:scheduled_classes, [:scheduled_at])

    create index(:scheduled_classes, [:branch_id])

    create index(:scheduled_classes, [:trainer_id])

    drop constraint(:scheduled_classes, "scheduled_classes_trainer_id_fkey")

    drop constraint(:scheduled_classes, "scheduled_classes_branch_id_fkey")

    drop constraint(:scheduled_classes, "scheduled_classes_class_definition_id_fkey")

    alter table(:scheduled_classes) do
      modify :class_definition_id,
             references(:class_definitions,
               column: :id,
               name: "scheduled_classes_class_definition_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :branch_id,
             references(:gym_branches,
               column: :id,
               name: "scheduled_classes_branch_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "scheduled_classes_trainer_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    create index(:member_subscriptions, [:subscription_plan_id])

    create index(:member_subscriptions, [:gym_id])

    create index(:member_subscriptions, [:member_id])

    drop constraint(:member_subscriptions, "member_subscriptions_gym_id_fkey")

    drop constraint(:member_subscriptions, "member_subscriptions_subscription_plan_id_fkey")

    drop constraint(:member_subscriptions, "member_subscriptions_member_id_fkey")

    alter table(:member_subscriptions) do
      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "member_subscriptions_member_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :subscription_plan_id,
             references(:subscription_plans,
               column: :id,
               name: "member_subscriptions_subscription_plan_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "member_subscriptions_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:member_invitations, [:invited_email])

    create index(:member_invitations, [:gym_id])

    drop constraint(:member_invitations, "member_invitations_branch_id_fkey")

    drop constraint(:member_invitations, "member_invitations_invited_by_id_fkey")

    drop constraint(:member_invitations, "member_invitations_gym_id_fkey")

    alter table(:member_invitations) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "member_invitations_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :invited_by_id,
             references(:users,
               column: :id,
               name: "member_invitations_invited_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :branch_id,
             references(:gym_branches,
               column: :id,
               name: "member_invitations_branch_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    create unique_index(:member_invitations, [:gym_id, :invited_email],
             name: "member_invitations_unique_pending_invitation_index",
             where: "(status = 'pending')"
           )

    drop constraint(:gyms, "gyms_owner_id_fkey")

    alter table(:gyms) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "gyms_owner_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create index(:gym_trainers, [:branch_id])

    create index(:gym_trainers, [:gym_id])

    create index(:gym_trainers, [:user_id])

    drop constraint(:gym_trainers, "gym_trainers_branch_id_fkey")

    drop constraint(:gym_trainers, "gym_trainers_gym_id_fkey")

    drop constraint(:gym_trainers, "gym_trainers_user_id_fkey")

    alter table(:gym_trainers) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "gym_trainers_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "gym_trainers_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :branch_id,
             references(:gym_branches,
               column: :id,
               name: "gym_trainers_branch_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    create index(:gym_members, [:assigned_trainer_id])

    create index(:gym_members, [:branch_id])

    create index(:gym_members, [:gym_id])

    create index(:gym_members, [:user_id])

    drop constraint(:gym_members, "gym_members_branch_id_fkey")

    drop constraint(:gym_members, "gym_members_assigned_trainer_id_fkey")

    drop constraint(:gym_members, "gym_members_gym_id_fkey")

    drop constraint(:gym_members, "gym_members_user_id_fkey")

    alter table(:gym_members) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "gym_members_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "gym_members_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :assigned_trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "gym_members_assigned_trainer_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :branch_id,
             references(:gym_branches,
               column: :id,
               name: "gym_members_branch_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    create index(:gym_branches, [:gym_id])

    drop constraint(:gym_branches, "gym_branches_gym_id_fkey")

    alter table(:gym_branches) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "gym_branches_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:diet_plans, [:gym_id])

    create index(:diet_plans, [:trainer_id])

    create index(:diet_plans, [:member_id])

    drop constraint(:diet_plans, "diet_plans_template_id_fkey")

    drop constraint(:diet_plans, "diet_plans_trainer_id_fkey")

    drop constraint(:diet_plans, "diet_plans_gym_id_fkey")

    drop constraint(:diet_plans, "diet_plans_member_id_fkey")

    alter table(:diet_plans) do
      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "diet_plans_member_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "diet_plans_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "diet_plans_trainer_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :template_id,
             references(:diet_plan_templates,
               column: :id,
               name: "diet_plans_template_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    create index(:diet_plan_templates, [:created_by_id])

    create index(:diet_plan_templates, [:gym_id])

    drop constraint(:diet_plan_templates, "diet_plan_templates_created_by_id_fkey")

    drop constraint(:diet_plan_templates, "diet_plan_templates_gym_id_fkey")

    alter table(:diet_plan_templates) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "diet_plan_templates_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :created_by_id,
             references(:users,
               column: :id,
               name: "diet_plan_templates_created_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    create index(:client_assignment_requests, [:trainer_id])

    create index(:client_assignment_requests, [:member_id])

    create index(:client_assignment_requests, [:gym_id])

    drop constraint(
           :client_assignment_requests,
           "client_assignment_requests_requested_by_id_fkey"
         )

    drop constraint(:client_assignment_requests, "client_assignment_requests_trainer_id_fkey")

    drop constraint(:client_assignment_requests, "client_assignment_requests_member_id_fkey")

    drop constraint(:client_assignment_requests, "client_assignment_requests_gym_id_fkey")

    alter table(:client_assignment_requests) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "client_assignment_requests_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "client_assignment_requests_member_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "client_assignment_requests_trainer_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :requested_by_id,
             references(:users,
               column: :id,
               name: "client_assignment_requests_requested_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:class_definitions, [:gym_id])

    drop constraint(:class_definitions, "class_definitions_gym_id_fkey")

    alter table(:class_definitions) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "class_definitions_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:class_bookings, [:scheduled_class_id])

    create index(:class_bookings, [:member_id])

    drop constraint(:class_bookings, "class_bookings_member_id_fkey")

    drop constraint(:class_bookings, "class_bookings_scheduled_class_id_fkey")

    alter table(:class_bookings) do
      modify :scheduled_class_id,
             references(:scheduled_classes,
               column: :id,
               name: "class_bookings_scheduled_class_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "class_bookings_member_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:attendance_records, [:attended_at])

    create index(:attendance_records, [:gym_id])

    create index(:attendance_records, [:member_id])

    drop constraint(:attendance_records, "attendance_records_marked_by_id_fkey")

    drop constraint(:attendance_records, "attendance_records_gym_id_fkey")

    drop constraint(:attendance_records, "attendance_records_member_id_fkey")

    alter table(:attendance_records) do
      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "attendance_records_member_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "attendance_records_gym_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :marked_by_id,
             references(:users,
               column: :id,
               name: "attendance_records_marked_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end
  end

  def down do
    drop constraint(:attendance_records, "attendance_records_member_id_fkey")

    drop constraint(:attendance_records, "attendance_records_gym_id_fkey")

    drop constraint(:attendance_records, "attendance_records_marked_by_id_fkey")

    alter table(:attendance_records) do
      modify :marked_by_id,
             references(:users,
               column: :id,
               name: "attendance_records_marked_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "attendance_records_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "attendance_records_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:attendance_records, [:member_id])

    drop_if_exists index(:attendance_records, [:gym_id])

    drop_if_exists index(:attendance_records, [:attended_at])

    drop constraint(:class_bookings, "class_bookings_scheduled_class_id_fkey")

    drop constraint(:class_bookings, "class_bookings_member_id_fkey")

    alter table(:class_bookings) do
      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "class_bookings_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :scheduled_class_id,
             references(:scheduled_classes,
               column: :id,
               name: "class_bookings_scheduled_class_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:class_bookings, [:member_id])

    drop_if_exists index(:class_bookings, [:scheduled_class_id])

    drop constraint(:class_definitions, "class_definitions_gym_id_fkey")

    alter table(:class_definitions) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "class_definitions_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:class_definitions, [:gym_id])

    drop constraint(:client_assignment_requests, "client_assignment_requests_gym_id_fkey")

    drop constraint(:client_assignment_requests, "client_assignment_requests_member_id_fkey")

    drop constraint(:client_assignment_requests, "client_assignment_requests_trainer_id_fkey")

    drop constraint(
           :client_assignment_requests,
           "client_assignment_requests_requested_by_id_fkey"
         )

    alter table(:client_assignment_requests) do
      modify :requested_by_id,
             references(:users,
               column: :id,
               name: "client_assignment_requests_requested_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "client_assignment_requests_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "client_assignment_requests_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "client_assignment_requests_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:client_assignment_requests, [:gym_id])

    drop_if_exists index(:client_assignment_requests, [:member_id])

    drop_if_exists index(:client_assignment_requests, [:trainer_id])

    drop constraint(:diet_plan_templates, "diet_plan_templates_gym_id_fkey")

    drop constraint(:diet_plan_templates, "diet_plan_templates_created_by_id_fkey")

    alter table(:diet_plan_templates) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "diet_plan_templates_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "diet_plan_templates_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:diet_plan_templates, [:gym_id])

    drop_if_exists index(:diet_plan_templates, [:created_by_id])

    drop constraint(:diet_plans, "diet_plans_member_id_fkey")

    drop constraint(:diet_plans, "diet_plans_gym_id_fkey")

    drop constraint(:diet_plans, "diet_plans_trainer_id_fkey")

    drop constraint(:diet_plans, "diet_plans_template_id_fkey")

    alter table(:diet_plans) do
      modify :template_id,
             references(:diet_plan_templates,
               column: :id,
               name: "diet_plans_template_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "diet_plans_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "diet_plans_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "diet_plans_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:diet_plans, [:member_id])

    drop_if_exists index(:diet_plans, [:trainer_id])

    drop_if_exists index(:diet_plans, [:gym_id])

    drop constraint(:gym_branches, "gym_branches_gym_id_fkey")

    alter table(:gym_branches) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "gym_branches_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:gym_branches, [:gym_id])

    drop constraint(:gym_members, "gym_members_user_id_fkey")

    drop constraint(:gym_members, "gym_members_gym_id_fkey")

    drop constraint(:gym_members, "gym_members_assigned_trainer_id_fkey")

    drop constraint(:gym_members, "gym_members_branch_id_fkey")

    alter table(:gym_members) do
      modify :branch_id,
             references(:gym_branches,
               column: :id,
               name: "gym_members_branch_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :assigned_trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "gym_members_assigned_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "gym_members_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "gym_members_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:gym_members, [:user_id])

    drop_if_exists index(:gym_members, [:gym_id])

    drop_if_exists index(:gym_members, [:branch_id])

    drop_if_exists index(:gym_members, [:assigned_trainer_id])

    drop constraint(:gym_trainers, "gym_trainers_user_id_fkey")

    drop constraint(:gym_trainers, "gym_trainers_gym_id_fkey")

    drop constraint(:gym_trainers, "gym_trainers_branch_id_fkey")

    alter table(:gym_trainers) do
      modify :branch_id,
             references(:gym_branches,
               column: :id,
               name: "gym_trainers_branch_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "gym_trainers_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "gym_trainers_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:gym_trainers, [:user_id])

    drop_if_exists index(:gym_trainers, [:gym_id])

    drop_if_exists index(:gym_trainers, [:branch_id])

    drop constraint(:gyms, "gyms_owner_id_fkey")

    alter table(:gyms) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "gyms_owner_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:member_invitations, [:gym_id, :invited_email],
                     name: "member_invitations_unique_pending_invitation_index"
                   )

    drop constraint(:member_invitations, "member_invitations_gym_id_fkey")

    drop constraint(:member_invitations, "member_invitations_invited_by_id_fkey")

    drop constraint(:member_invitations, "member_invitations_branch_id_fkey")

    alter table(:member_invitations) do
      modify :branch_id,
             references(:gym_branches,
               column: :id,
               name: "member_invitations_branch_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :invited_by_id,
             references(:users,
               column: :id,
               name: "member_invitations_invited_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "member_invitations_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:member_invitations, [:gym_id])

    drop_if_exists index(:member_invitations, [:invited_email])

    drop constraint(:member_subscriptions, "member_subscriptions_member_id_fkey")

    drop constraint(:member_subscriptions, "member_subscriptions_subscription_plan_id_fkey")

    drop constraint(:member_subscriptions, "member_subscriptions_gym_id_fkey")

    alter table(:member_subscriptions) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "member_subscriptions_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :subscription_plan_id,
             references(:subscription_plans,
               column: :id,
               name: "member_subscriptions_subscription_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "member_subscriptions_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:member_subscriptions, [:member_id])

    drop_if_exists index(:member_subscriptions, [:gym_id])

    drop_if_exists index(:member_subscriptions, [:subscription_plan_id])

    drop constraint(:scheduled_classes, "scheduled_classes_class_definition_id_fkey")

    drop constraint(:scheduled_classes, "scheduled_classes_branch_id_fkey")

    drop constraint(:scheduled_classes, "scheduled_classes_trainer_id_fkey")

    alter table(:scheduled_classes) do
      modify :trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "scheduled_classes_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :branch_id,
             references(:gym_branches,
               column: :id,
               name: "scheduled_classes_branch_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :class_definition_id,
             references(:class_definitions,
               column: :id,
               name: "scheduled_classes_class_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:scheduled_classes, [:trainer_id])

    drop_if_exists index(:scheduled_classes, [:branch_id])

    drop_if_exists index(:scheduled_classes, [:scheduled_at])

    drop_if_exists index(:scheduled_classes, [:class_definition_id])

    drop constraint(:subscription_plans, "subscription_plans_gym_id_fkey")

    alter table(:subscription_plans) do
      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "subscription_plans_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:subscription_plans, [:gym_id])

    drop_if_exists unique_index(:trainer_invitations, [:gym_id, :invited_email],
                     name: "trainer_invitations_unique_pending_invitation_index"
                   )

    drop constraint(:trainer_invitations, "trainer_invitations_gym_id_fkey")

    drop constraint(:trainer_invitations, "trainer_invitations_invited_by_id_fkey")

    alter table(:trainer_invitations) do
      modify :invited_by_id,
             references(:users,
               column: :id,
               name: "trainer_invitations_invited_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "trainer_invitations_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:trainer_invitations, [:gym_id])

    drop_if_exists index(:trainer_invitations, [:invited_email])

    drop constraint(:workout_plan_templates, "workout_plan_templates_gym_id_fkey")

    drop constraint(:workout_plan_templates, "workout_plan_templates_created_by_id_fkey")

    alter table(:workout_plan_templates) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "workout_plan_templates_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "workout_plan_templates_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:workout_plan_templates, [:gym_id])

    drop_if_exists index(:workout_plan_templates, [:created_by_id])

    drop constraint(:workout_plans, "workout_plans_member_id_fkey")

    drop constraint(:workout_plans, "workout_plans_gym_id_fkey")

    drop constraint(:workout_plans, "workout_plans_trainer_id_fkey")

    drop constraint(:workout_plans, "workout_plans_template_id_fkey")

    alter table(:workout_plans) do
      modify :template_id,
             references(:workout_plan_templates,
               column: :id,
               name: "workout_plans_template_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :trainer_id,
             references(:gym_trainers,
               column: :id,
               name: "workout_plans_trainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :gym_id,
             references(:gyms,
               column: :id,
               name: "workout_plans_gym_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :member_id,
             references(:gym_members,
               column: :id,
               name: "workout_plans_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:workout_plans, [:member_id])

    drop_if_exists index(:workout_plans, [:trainer_id])

    drop_if_exists index(:workout_plans, [:gym_id])
  end
end
